import { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ProductProvider from "@/contexts/ProductContext";
import SidebarProvider from "@/contexts/SidebarContext";
import CartProvider from "@/contexts/CartContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <CartProvider>
            <ProductProvider>
             {children}
            </ProductProvider>
          </CartProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
